### ISSUE TITLE
Compile instructions...

### ISSUE THREAD

**Issue by cesarbrod** [tialaramex/sparql-query#4]
Although I have installed all of the prerrequisites, I have not been able to compile. I am not a "experienced" developer so a binary package, if available, will also help me. Thanks for any help! Here is my compilation output:

fatal: Not a git repository (or any of the parent directories): .git
cc -std=gnu99 -Wall -DGIT_REV=\"\"  -g -O2 `pkg-config --cflags glib-2.0 libcurl libxml-2.0`   -c -o sparql-query.o sparql-query.c
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing`libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
sparql-query.c:25:18: fatal error: glib.h: Arquivo ou diretório não encontrado
compilation terminated.
make: *\* [sparql-query.o] Erro 1

I assume, by looking at the first error, I must somehow transform the directory where I downloaded the sources a git directory and I don't know how to do it.

All the best!

Cesar

**Comment by tialaramex** [comment]
Don't worry about the .git error unless you are using git. The rest of the errors suggest that although you felt confident you have all the pre-requisites either you do not, or they were installed somewhere unexpected and could not be found.

You may be able to use 'locate' to find files like glib-2.0.pc and libxml-2.0.pc and add the directory where you found them to the PKG_CONFIG_PATH variable appropriately. Or they may not exist, in which case you should install them. For example, on an RPM-based Linux distribution you need to install packages with -devel (meaning for development) as well as the packages with just the library in them.

For example, if somehow you have these .pc files in /some/unusual/directory  you can write

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/some/unusual/directory

Good luck.

**Comment by cesarbrod** [comment]
Thanks! Got it compiled after installing the dev packages libcurl4-gnutls-dev, libglib2.0-dev, libxml-2.0.pc, libreadline-dev and its dependencies. In my case the command

sudo apt-get install  libcurl4-gnutls-dev libglib2.0-dev libxml-2.0.pc libreadline-dev

did the required magic. Just decided to register this in here in case it may be helpful for some other newbie like me! ;)

**Comment by hanynowsky** [comment]
In case of a CENTOS:

$~ locate libcurl.pc
 /usr/lib64/pkgconfig/libcurl.pc
$~ export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib64/pkgconfig/
$~ /usr/bin/curl-config --libs
-L/usr/lib64 -lcurl
