### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by cesarbrod** [tialaramex/sparql-query#5]
I am trying to build on top of the example on your wiki and also using some more sources on the web. Regardless what I try, I always get the full HTML source for the index page of the site I am using. I did the Google Rich Snippets to check if I did get the info I was looking for on sparql-query. Here are some examples:
1. Trying to get authors for the posts
# sparql-query http://www.kafermoveis.com.br

sparql$ PREFIX foaf: http://xmlns.com/foaf/0.1/
      $ SELECT ?name FROM http://www.kafermoveis.com.br
      $ WHERE
      $ {
      $ ?x foaf:name ?name
      $ }
      $ ;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
(...)
1. Trying to get the titles

sparql$ PREFIX element:http://purl.org/dc/elements/1.1/
PREFIX term:http://purl.org/de/terms/
SELECT ?uri ?area WHERE { ?uri element:title ""; term:isPartOf [ element:title ?area ] };
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
(...)
1. Trying to reproduce the wiki example

sparql-query http://www.rdfabout.com
sparql$ PREFIX element: http://purl.org/dc/elements/1.1/
      $ PREFIX term: http://purl.org/dc/terms/
      $ SELECT ?uri ?area WHERE { ?uri element:title "Southhampton"; term:isPartOf [ element:title ?area ] };
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml"><head><title> 
(...)

I am definately doing something wrong and I thank you for all your help!

**Comment by tialaramex** [comment]
The site you're connecting to, http://www.kafermoveis.com.br/ does not appear to be a SPARQL endpoint. You need to specify an endpoint for a query service that supports the SPARQL protocol 1.0 or later. I am closing this issue report because I don't think the problem you're having is related to the sparql-query tool at all.
