### ISSUE TITLE
Tag to facilitate downloading

### ISSUE THREAD

**Issue by wwaites** [tialaramex/sparql-query#6]
The most recent tag is 0.2 from 2009. Would be good to have a current one so that we have a download link to recent source tarball. I'll use this to make a FreeBSD port.

**Comment by tialaramex** [comment]
I have created a tag v1.0 because I think the sparql-query tool is useful and in some sense "complete" in its current state, and although some major features could be possible it's more likely future work will mostly be bugfixes. I hope the tag is helpful.

**Comment by wwaites** [comment]
Thank you!
