### ISSUE TITLE
Trouble compiling on ubuntu onereric ocelot

### ISSUE THREAD

**Issue by stuaxo** [tialaramex/sparql-query#7]
Have installed glib-dev, lib-curl - get this error:

stu@berv:~/projects/sparql-query$ make
cc  `pkg-config --libs glib-2.0 libcurl libxml-2.0` -lreadline -lncurses -o sparql-query sparql-query.o result-parse.o scan-sparql.o
sparql-query.o: In function `sparql_curl_init':
/home/stu/projects/sparql-query/sparql-query.c:218: undefined reference to`curl_easy_init'
/home/stu/projects/sparql-query/sparql-query.c:224: undefined reference to `g_strdup_printf'
/home/stu/projects/sparql-query/sparql-query.c:226: undefined reference to`curl_slist_append'
/home/stu/projects/sparql-query/sparql-query.c:227: undefined reference to `g_free'
/home/stu/projects/sparql-query/sparql-query.c:229: undefined reference to`curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:222: undefined reference to `g_strdup_printf'
sparql-query.o: In function`my_header_fn':
/home/stu/projects/sparql-query/sparql-query.c:252: undefined reference to `curl_easy_setopt'
sparql-query.o: In function`execute_operation':
/home/stu/projects/sparql-query/sparql-query.c:273: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/sparql-query.c:275: undefined reference to`g_free'
/home/stu/projects/sparql-query/sparql-query.c:277: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/sparql-query.c:292: undefined reference to`g_free'
/home/stu/projects/sparql-query/sparql-query.c:270: undefined reference to `g_strjoin'
/home/stu/projects/sparql-query/sparql-query.c:289: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/sparql-query.c:299: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:300: undefined reference to`curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:301: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:302: undefined reference to`curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:303: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:313: undefined reference to`curl_easy_perform'
/home/stu/projects/sparql-query/sparql-query.c:328: undefined reference to `g_free'
/home/stu/projects/sparql-query/sparql-query.c:281: undefined reference to`curl_easy_escape'
/home/stu/projects/sparql-query/sparql-query.c:283: undefined reference to `g_strdup_printf'
/home/stu/projects/sparql-query/sparql-query.c:287: undefined reference to`curl_free'
/home/stu/projects/sparql-query/sparql-query.c:307: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:308: undefined reference to`curl_easy_escape'
/home/stu/projects/sparql-query/sparql-query.c:309: undefined reference to `g_strdup_printf'
/home/stu/projects/sparql-query/sparql-query.c:310: undefined reference to`curl_free'
/home/stu/projects/sparql-query/sparql-query.c:311: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:285: undefined reference to`g_strdup_printf'
sparql-query.o: In function `history_filename':
/home/stu/projects/sparql-query/sparql-query.c:195: undefined reference to`g_get_home_dir'
/home/stu/projects/sparql-query/sparql-query.c:193: undefined reference to `g_get_home_dir'
sparql-query.o: In function`sparql_curl_init':
/home/stu/projects/sparql-query/sparql-query.c:230: undefined reference to `curl_easy_setopt'
sparql-query.o: In function`history_filename':
/home/stu/projects/sparql-query/sparql-query.c:195: undefined reference to `g_strconcat'
/home/stu/projects/sparql-query/sparql-query.c:193: undefined reference to`g_strconcat'
sparql-query.o: In function `interactive':
/home/stu/projects/sparql-query/sparql-query.c:374: undefined reference to`rl_insert'
/home/stu/projects/sparql-query/sparql-query.c:374: undefined reference to `rl_bind_key'
sparql-query.o: In function`load_history_dotfile':
/home/stu/projects/sparql-query/sparql-query.c:204: undefined reference to `read_history'
/home/stu/projects/sparql-query/sparql-query.c:205: undefined reference to`g_free'
sparql-query.o: In function `check_endpoint':
/home/stu/projects/sparql-query/sparql-query.c:338: undefined reference to`curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:344: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:346: undefined reference to`curl_easy_setopt'
sparql-query.o: In function `interactive':
/home/stu/projects/sparql-query/sparql-query.c:394: undefined reference to`readline'
/home/stu/projects/sparql-query/sparql-query.c:397: undefined reference to `g_free'
/home/stu/projects/sparql-query/sparql-query.c:398: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/sparql-query.c:405: undefined reference to `g_str_has_suffix'
/home/stu/projects/sparql-query/sparql-query.c:407: undefined reference to`readline'
/home/stu/projects/sparql-query/sparql-query.c:410: undefined reference to `g_strjoin'
/home/stu/projects/sparql-query/sparql-query.c:411: undefined reference to`g_free'
/home/stu/projects/sparql-query/sparql-query.c:415: undefined reference to `add_history'
/home/stu/projects/sparql-query/sparql-query.c:417: undefined reference to`g_strconcat'
/home/stu/projects/sparql-query/sparql-query.c:418: undefined reference to `g_free'
/home/stu/projects/sparql-query/sparql-query.c:421: undefined reference to`g_str_has_suffix'
sparql-query.o: In function `save_history_dotfile':
/home/stu/projects/sparql-query/sparql-query.c:211: undefined reference to`stifle_history'
/home/stu/projects/sparql-query/sparql-query.c:212: undefined reference to `write_history'
/home/stu/projects/sparql-query/sparql-query.c:213: undefined reference to`g_free'
sparql-query.o: In function `interactive':
/home/stu/projects/sparql-query/sparql-query.c:378: undefined reference to`using_history'
sparql-query.o: In function `check_endpoint':
/home/stu/projects/sparql-query/sparql-query.c:339: undefined reference to`curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:340: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/sparql-query.c:341: undefined reference to`curl_easy_perform'
result-parse.o: In function `xml_characters':
/home/stu/projects/sparql-query/result-parse.c:453: undefined reference to`g_strndup'
/home/stu/projects/sparql-query/result-parse.c:454: undefined reference to `g_strconcat'
/home/stu/projects/sparql-query/result-parse.c:455: undefined reference to`g_free'
/home/stu/projects/sparql-query/result-parse.c:458: undefined reference to `g_strndup'
result-parse.o: In function`xml_start_element':
/home/stu/projects/sparql-query/result-parse.c:269: undefined reference to `g_free'
/home/stu/projects/sparql-query/result-parse.c:165: undefined reference to`g_utf8_strlen'
/home/stu/projects/sparql-query/result-parse.c:167: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/result-parse.c:167: undefined reference to`g_slist_append'
result-parse.o: In function `sr_parse':
/home/stu/projects/sparql-query/result-parse.c:472: undefined reference to`g_malloc0'
/home/stu/projects/sparql-query/result-parse.c:516: undefined reference to `xmlSAXUserParseFile'
/home/stu/projects/sparql-query/result-parse.c:518: undefined reference to`xmlSAXUserParseFile'
/home/stu/projects/sparql-query/result-parse.c:520: undefined reference to `g_free'
/home/stu/projects/sparql-query/result-parse.c:522: undefined reference to`g_free'
result-parse.o: In function `sr_utf8_column_width':
/home/stu/projects/sparql-query/result-parse.c:533: undefined reference to`g_utf8_to_ucs4_fast'
/home/stu/projects/sparql-query/result-parse.c:536: undefined reference to `g_unichar_iswide'
/home/stu/projects/sparql-query/result-parse.c:538: undefined reference to`g_unichar_iszerowidth'
/home/stu/projects/sparql-query/result-parse.c:544: undefined reference to `g_free'
result-parse.o: In function`xml_end_element':
/home/stu/projects/sparql-query/result-parse.c:366: undefined reference to `g_strdup_printf'
/home/stu/projects/sparql-query/result-parse.c:283: undefined reference to`g_malloc0_n'
/home/stu/projects/sparql-query/result-parse.c:284: undefined reference to `g_malloc0_n'
/home/stu/projects/sparql-query/result-parse.c:285: undefined reference to`g_malloc0_n'
/home/stu/projects/sparql-query/result-parse.c:395: undefined reference to `g_free'
/home/stu/projects/sparql-query/result-parse.c:353: undefined reference to`g_strdup_printf'
/home/stu/projects/sparql-query/result-parse.c:340: undefined reference to `g_strdup_printf'
result-parse.o: In function`xml_characters':
/home/stu/projects/sparql-query/result-parse.c:456: undefined reference to `g_free'
scan-sparql.o: In function`scan_init':
/home/stu/projects/sparql-query/scan-sparql.c:39: undefined reference to `g_regex_new'
/home/stu/projects/sparql-query/scan-sparql.c:54: undefined reference to`g_error_free'
/home/stu/projects/sparql-query/scan-sparql.c:49: undefined reference to `g_regex_new'
/home/stu/projects/sparql-query/scan-sparql.c:59: undefined reference to`g_free'
/home/stu/projects/sparql-query/scan-sparql.c:59: undefined reference to `g_str_hash'
/home/stu/projects/sparql-query/scan-sparql.c:59: undefined reference to`g_str_equal'
/home/stu/projects/sparql-query/scan-sparql.c:59: undefined reference to `g_hash_table_new_full'
/home/stu/projects/sparql-query/scan-sparql.c:65: undefined reference to`g_key_file_load_from_file'
/home/stu/projects/sparql-query/scan-sparql.c:69: undefined reference to `g_log'
/home/stu/projects/sparql-query/scan-sparql.c:77: undefined reference to`g_key_file_get_keys'
/home/stu/projects/sparql-query/scan-sparql.c:80: undefined reference to `g_key_file_get_string'
/home/stu/projects/sparql-query/scan-sparql.c:82: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:82: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:82: undefined reference to`g_hash_table_insert'
/home/stu/projects/sparql-query/scan-sparql.c:85: undefined reference to `g_free'
/home/stu/projects/sparql-query/scan-sparql.c:73: undefined reference to`g_error_free'
/home/stu/projects/sparql-query/scan-sparql.c:62: undefined reference to `g_key_file_new'
/home/stu/projects/sparql-query/scan-sparql.c:63: undefined reference to`g_get_home_dir'
/home/stu/projects/sparql-query/scan-sparql.c:63: undefined reference to `g_strconcat'
scan-sparql.o: In function`scan_fini':
/home/stu/projects/sparql-query/scan-sparql.c:95: undefined reference to `g_regex_unref'
/home/stu/projects/sparql-query/scan-sparql.c:99: undefined reference to`g_regex_unref'
/home/stu/projects/sparql-query/scan-sparql.c:103: undefined reference to `g_hash_table_unref'
/home/stu/projects/sparql-query/scan-sparql.c:110: undefined reference to`g_key_file_to_data'
/home/stu/projects/sparql-query/scan-sparql.c:111: undefined reference to `g_file_set_contents'
/home/stu/projects/sparql-query/scan-sparql.c:112: undefined reference to`g_key_file_free'
/home/stu/projects/sparql-query/scan-sparql.c:114: undefined reference to `g_free'
/home/stu/projects/sparql-query/scan-sparql.c:115: undefined reference to`g_free'
scan-sparql.o: In function `scan_sparql':
/home/stu/projects/sparql-query/scan-sparql.c:132: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:134: undefined reference to `g_regex_match'
/home/stu/projects/sparql-query/scan-sparql.c:150: undefined reference to`g_match_info_next'
/home/stu/projects/sparql-query/scan-sparql.c:135: undefined reference to `g_match_info_matches'
/home/stu/projects/sparql-query/scan-sparql.c:136: undefined reference to`g_match_info_fetch'
/home/stu/projects/sparql-query/scan-sparql.c:137: undefined reference to `g_match_info_fetch'
/home/stu/projects/sparql-query/scan-sparql.c:139: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:139: undefined reference to `g_slist_prepend'
/home/stu/projects/sparql-query/scan-sparql.c:140: undefined reference to`g_hash_table_lookup'
/home/stu/projects/sparql-query/scan-sparql.c:143: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:143: undefined reference to`g_hash_table_replace'
/home/stu/projects/sparql-query/scan-sparql.c:148: undefined reference to `g_key_file_set_string'
/home/stu/projects/sparql-query/scan-sparql.c:152: undefined reference to`g_match_info_free'
/home/stu/projects/sparql-query/scan-sparql.c:159: undefined reference to `g_regex_match'
/home/stu/projects/sparql-query/scan-sparql.c:160: undefined reference to`g_match_info_matches'
/home/stu/projects/sparql-query/scan-sparql.c:161: undefined reference to `g_match_info_fetch'
/home/stu/projects/sparql-query/scan-sparql.c:209: undefined reference to`g_free'
/home/stu/projects/sparql-query/scan-sparql.c:210: undefined reference to `g_match_info_next'
/home/stu/projects/sparql-query/scan-sparql.c:160: undefined reference to`g_match_info_matches'
/home/stu/projects/sparql-query/scan-sparql.c:212: undefined reference to `g_match_info_free'
/home/stu/projects/sparql-query/scan-sparql.c:215: undefined reference to`g_free'
/home/stu/projects/sparql-query/scan-sparql.c:217: undefined reference to `g_slist_free'
/home/stu/projects/sparql-query/scan-sparql.c:171: undefined reference to`g_hash_table_lookup'
/home/stu/projects/sparql-query/scan-sparql.c:176: undefined reference to `g_strdup_printf'
/home/stu/projects/sparql-query/scan-sparql.c:177: undefined reference to`g_free'
/home/stu/projects/sparql-query/scan-sparql.c:178: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:178: undefined reference to`g_slist_prepend'
/home/stu/projects/sparql-query/scan-sparql.c:147: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:147: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:147: undefined reference to `g_hash_table_insert'
/home/stu/projects/sparql-query/scan-sparql.c:180: undefined reference to`curl_easy_init'
/home/stu/projects/sparql-query/scan-sparql.c:182: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/scan-sparql.c:183: undefined reference to`g_strdup_printf'
/home/stu/projects/sparql-query/scan-sparql.c:184: undefined reference to `curl_easy_setopt'
/home/stu/projects/sparql-query/scan-sparql.c:185: undefined reference to`curl_easy_perform'
/home/stu/projects/sparql-query/scan-sparql.c:187: undefined reference to `curl_easy_getinfo'
/home/stu/projects/sparql-query/scan-sparql.c:188: undefined reference to`g_free'
/home/stu/projects/sparql-query/scan-sparql.c:204: undefined reference to `curl_easy_cleanup'
/home/stu/projects/sparql-query/scan-sparql.c:201: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:201: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:201: undefined reference to`g_hash_table_insert'
/home/stu/projects/sparql-query/scan-sparql.c:195: undefined reference to `g_strdup_printf'
/home/stu/projects/sparql-query/scan-sparql.c:196: undefined reference to`g_free'
/home/stu/projects/sparql-query/scan-sparql.c:197: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:197: undefined reference to`g_slist_prepend'
/home/stu/projects/sparql-query/scan-sparql.c:198: undefined reference to `g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:198: undefined reference to`g_strdup'
/home/stu/projects/sparql-query/scan-sparql.c:198: undefined reference to `g_hash_table_insert'
/home/stu/projects/sparql-query/scan-sparql.c:199: undefined reference to`g_key_file_set_string'
collect2: ld returned 1 exit status
make: **\* [sparql-query] Error 1

**Comment by swh** [comment]
Looks like your curl-dev, glib-dev, and readline instals didn't work properly.

Sorry, not familiar with Ubuntu. Possibly running ldconfig as root will help?
- Steve

**Comment by stuaxo** [comment]
ldconfig as root doesn't seem to help.

I check the output of pkgconfig and it seems to find the libraries:

stu@berv:~/projects/sparql-query$ pkg-config --libs glib-2.0 libcurl libxml-2.0
-lglib-2.0 -lcurl -lxml2 

From: Steve Harris reply@reply.github.com

To: stuaxo stuaxo2@yahoo.com 

> Sent: Wednesday, February 1, 2012 3:41 PM
> Subject: Re: [sparql-query] Trouble compiling on ubuntu onereric ocelot (#7)
> 
> Looks like your curl-dev, glib-dev, and readline instals didn't work properly.
> 
> Sorry, not familiar with Ubuntu. Possibly running ldconfig as root will help?
> - Steve

**Comment by swh** [comment]
Can you try editing the Makefile, and putting the .o files before the pkg-config, and -l elements?

**Comment by stuaxo** [comment]
Cool, that seems to work - it generates a binary and it runs, haven't had a chance to see if it's completely correct.

Heres the very tiny diff for that https://gist.github.com/1718226 

diff --git a/Makefile b/Makefile
index 14c89d8..ab6cd16 100644
--- a/Makefile
+++ b/Makefile
@@ -25,4 +25,4 @@ scan-test: scan-test.o scan-sparql.o
 $(CC) $(LDFLAGS) -o $@ $^

sparql-query: sparql-query.o result-parse.o scan-sparql.o
- $(CC) $(LDFLAGS) -o $@ $^
- $(CC) -o $@ $^ $(LDFLAGS)

**Comment by tialaramex** [comment]
Fixed in new HEAD, hopefully. Still not quite sure I understand how the linker decides the "right" order you should use here, but this doesn't break anything for me and seems more correct according to the documentation.

**Comment by swh** [comment]
I've seen this with 4store as well, something about that Ubuntu version of gcc is really fussy about linker order - it's like the bad old days :(
