### ISSUE TITLE
Trouble Compiling on OS X

### ISSUE THREAD

**Issue by scogle** [tialaramex/sparql-query#8]
I'm sorry if this may seem like a very basic question or if it's been answered elsewhere, but I don't have much experience compiling things myself.  When I try to run `sudo make install` on OS X I get this:

```
mkdir -p /usr/local/bin/
install sparql-query /usr/local/bin/
install: sparql-query: No such file or directory
make: *** [install] Error 71
```

I'm not totally sure if this is indicating that I'm missing a dependency or that something else has gone wrong.  Any guidance would be much appreciated as this seems like a very useful tool.

**Comment by tialaramex** [comment]
The problem is a poorly written Makefile. I will fix this shortly.

Meanwhile though you should find that typing the following commands in order is effective, or at least brings progress:
make
make sparql-update
make install

Please let me know if this doesn't help.

**Comment by scogle** [comment]
Thanks, that worked for me.  You may want to add pkg-config as a dependency since my system apparently did not have it.  Once I figure that out everything worked fine though.  Thanks for making this great tool.
