### ISSUE TITLE
“Undefined references” when linking in Linux (Ubuntu)

### ISSUE THREAD

**Issue by matthewmarkus** [tialaramex/sparql-query#9]
It only worked after I changed the final command in the Makefile so that the libraries were referenced last:

```
diff Makefile Makefile.old 
28c28
<   $(CC) -o $@ $^ $(LDFLAGS)

---
>   $(CC) $(LDFLAGS) -o $@ $^
```

**Comment by matthewmarkus** [comment]
This is a duplicate of Issue #7. I didn't realize this was already fixed in the head.

**Comment by swh** [comment]
Did you download a tarball from somewhere? If so we should update it I guess.

**Comment by matthewmarkus** [comment]
Yeah, I grabbed the latest release (v1.0 - Oct 9, 2011) from here:
https://github.com/tialaramex/sparql-query/releases

**Comment by swh** [comment]
Great, thanks - forgot we did that! Github seems to have a version tagging and releasing function, so I used that to make a 1.1.
